{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloud-sentinel-k8s.fullname" . }}
  labels:
    {{- include "cloud-sentinel-k8s.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloud-sentinel-k8s.fullname" . }}
  labels:
    {{- include "cloud-sentinel-k8s.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloud-sentinel-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloud-sentinel-k8s.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}